[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --preload app:app"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3