# -*- coding: utf-8 -*-
"""test_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fijG4IwCywr04vGa7qoJbcHxvbjOwmJZ
"""

#!/usr/bin/env python3
import requests
import json
import tempfile
import os

def test_api(api_url):
    """Test the data analyst API"""

    print(f"Testing API at: {api_url}")

    # Test 1: Health check
    try:
        health_response = requests.get(api_url.replace('/api/', '/health'), timeout=10)
        print(f"Health check: {health_response.status_code} - {health_response.json()}")
    except Exception as e:
        print(f"Health check failed: {e}")

    # Test 2: Home page
    try:
        home_response = requests.get(api_url.replace('/api/', '/'), timeout=10)
        print(f"Home page: {home_response.status_code} - {home_response.json()}")
    except Exception as e:
        print(f"Home page failed: {e}")

    # Test 3: Main API with film analysis
    test_questions = """Scrape the list of highest grossing films from Wikipedia. It is at the URL:
https://en.wikipedia.org/wiki/List_of_highest-grossing_films

Answer the following questions and respond with a JSON array of strings containing the answer.

1. How many $2 bn movies were released before 2000?
2. Which is the earliest film that grossed over $1.5 bn?
3. What's the correlation between the Rank and Peak?
4. Draw a scatterplot of Rank and Peak along with a dotted red regression line through it.
   Return as a base-64 encoded data URI, `"data:image/png;base64,iVBORw0KG..."`"""

    # Create temporary questions file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write(test_questions)
        questions_path = f.name

    try:
        # Test the main API endpoint
        with open(questions_path, 'rb') as f:
            files = {'questions.txt': f}

            print("Sending request to API...")
            response = requests.post(api_url, files=files, timeout=300)  # 5 minute timeout

            print(f"Status Code: {response.status_code}")
            print(f"Response Headers: {dict(response.headers)}")

            if response.status_code == 200:
                try:
                    result = response.json()
                    print("SUCCESS! API Response:")
                    if isinstance(result, list):
                        for i, item in enumerate(result):
                            if isinstance(item, str) and item.startswith('data:image'):
                                print(f"  [{i}]: [BASE64 IMAGE - {len(item)} characters]")
                            else:
                                print(f"  [{i}]: {item}")
                    else:
                        print(json.dumps(result, indent=2))
                except json.JSONDecodeError as e:
                    print(f"JSON decode error: {e}")
                    print(f"Raw response: {response.text[:500]}...")
            else:
                print(f"ERROR: {response.status_code}")
                print(f"Response: {response.text}")

    except requests.exceptions.Timeout:
        print("Request timed out after 5 minutes")
    except Exception as e:
        print(f"Request failed: {e}")
    finally:
        # Cleanup
        if os.path.exists(questions_path):
            os.unlink(questions_path)

if __name__ == "__main__":
    # Replace with your actual deployed URL
    API_URL = input("Enter your API URL (e.g., https://your-app.herokuapp.com/api/): ").strip()

    if not API_URL:
        API_URL = "http://localhost:5000/api/"  # Default to local
        print(f"Using default URL: {API_URL}")

    test_api(API_URL)